// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSvtCbTyrEIpry6NSiWBpyL6KU_P4LR-I',
    appId: '1:1089177983135:web:3fa3330a668ac788a4aaaa',
    messagingSenderId: '1089177983135',
    projectId: 'class-8804f',
    authDomain: 'class-8804f.firebaseapp.com',
    databaseURL: 'https://class-8804f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'class-8804f.firebasestorage.app',
    measurementId: 'G-2BKYTG1TDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf_0SPDvRcFrrLOQANrZKjFMH7xXnKTbk',
    appId: '1:1089177983135:android:5ac7aa8136e2a16ca4aaaa',
    messagingSenderId: '1089177983135',
    projectId: 'class-8804f',
    databaseURL: 'https://class-8804f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'class-8804f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYOhfq1FHSu594PvpNQq9TPjMAjOQ_dMo',
    appId: '1:1089177983135:ios:bb1883209133cf5ca4aaaa',
    messagingSenderId: '1089177983135',
    projectId: 'class-8804f',
    databaseURL: 'https://class-8804f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'class-8804f.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYOhfq1FHSu594PvpNQq9TPjMAjOQ_dMo',
    appId: '1:1089177983135:ios:bb1883209133cf5ca4aaaa',
    messagingSenderId: '1089177983135',
    projectId: 'class-8804f',
    databaseURL: 'https://class-8804f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'class-8804f.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSvtCbTyrEIpry6NSiWBpyL6KU_P4LR-I',
    appId: '1:1089177983135:web:f7fd41ec3ea95ccea4aaaa',
    messagingSenderId: '1089177983135',
    projectId: 'class-8804f',
    authDomain: 'class-8804f.firebaseapp.com',
    databaseURL: 'https://class-8804f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'class-8804f.firebasestorage.app',
    measurementId: 'G-BECV9NFWED',
  );
}
